# Q1. Pandas version


In [1]:
import pandas as pd


In [2]:
print(pd.__version__)



2.3.2


# Q2. Records count


In [71]:

data =  pd.read_csv("car_fuel_efficiency.csv")
print(data.shape)



(9704, 11)


# Q3. Fuel types


In [23]:

print(data.columns)

fuel_types = list(data['fuel_type'].unique())

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')


In [24]:
len(fuel_types)

2

# Q4. Missing values
How many columns in the dataset have missing values?



In [25]:
type(data)

pandas.core.frame.DataFrame

In [26]:
data.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [27]:
columns_with_missing_indicator =data.isna().any()
columns_with_missing_indicator

engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

In [29]:
type(columns_with_missing_indicator)

pandas.core.series.Series

In [31]:
data['num_doors'].describe()

count    9202.000000
mean       -0.006412
std         1.048162
min        -4.000000
25%        -1.000000
50%         0.000000
75%         1.000000
max         4.000000
Name: num_doors, dtype: float64

# Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?



In [32]:
data.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [33]:
data['origin']

0       Europe
1          USA
2       Europe
3          USA
4       Europe
         ...  
9699    Europe
9700       USA
9701       USA
9702       USA
9703      Asia
Name: origin, Length: 9704, dtype: object

In [36]:
data_asia = data[data['origin'] == 'Asia']
data_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [37]:
data_asia['fuel_efficiency_mpg'].max()

23.759122836520497

# Q6. Median value of horsepower
Find the median value of horsepower column in the dataset.

Next, calculate the most frequent value of the same horsepower column.

Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

Now, calculate the median value of horsepower once again.

Has it changed?

Yes, it increased
Yes, it decreased
No


In [72]:
data.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [73]:
data['horsepower'].median()

149.0

#### Next, calculate the most frequent value of the same horsepower column.



In [74]:
data['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [75]:
data['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [76]:
data['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
46.0       1
43.0       1
53.0       1
66.0       1
61.0       1
Name: count, Length: 192, dtype: int64

In [77]:
most_frequent_value = data['horsepower'].mode()
most_frequent_value[0]

np.float64(152.0)

#### Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.



In [80]:

# Fill missing values in all columns with their respective modes
horse_power_filled_with_mode = data['horsepower'].fillna(data['horsepower'].mode()[0])

print("\nDataFrame after filling all NaNs with column-wise modes:")
print(horse_power_filled_with_mode)


DataFrame after filling all NaNs with column-wise modes:
0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64


In [82]:
data['horsepower']=horse_power_filled_with_mode
data['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

#### Now, calculate the median value of horsepower once again.



In [83]:
data['horsepower'].median()

152.0

Has it changed?

Yes, it increased
Yes, it decreased
No

# Q7. Sum of weights
Select all the cars from Asia

Select only columns vehicle_weight and model_year

Select the first 7 values

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?



#### Select all the cars from Asia


In [147]:
data_asia = data[data['origin'] == 'Asia']
data_asia.shape

(3247, 11)

#### Select only columns vehicle_weight and model_year


In [148]:
data_asia.columns 

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [149]:
data_asia= data_asia[[ 'vehicle_weight','model_year']]

In [151]:
data_asia.columns, data_asia.shape

(Index(['vehicle_weight', 'model_year'], dtype='object'), (3247, 2))

#### Select the first 7 values




In [152]:
data_asia = data_asia.head(7)

In [153]:
data_asia.shape

(7, 2)

#### Get the underlying NumPy array. Let's call it X.



In [154]:
X = data_asia.to_numpy()

In [155]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.


In [156]:
XTX= np.dot(X, X.T)

In [159]:
XTX, XTX.shape

(array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
         10111792.75336224, 11282536.19632532, 11780081.29349753,
         14281180.86123177],
        [11608190.92541486, 11790026.46575708, 14007802.20739725,
         10255171.44187306, 11455668.70489329, 11966096.78727446,
         14531088.48421337],
        [13770311.23387465, 14007802.20739725, 16863697.77478558,
         12031947.83608462, 13574023.463935  , 14232076.05656009,
         17530181.51805091],
        [10111792.75336224, 10255171.44187306, 12031947.83608462,
          9025088.58092514,  9989516.7638366 , 10397924.16669749,
         12456257.9230991 ],
        [11282536.19632532, 11455668.70489329, 13574023.463935  ,
          9989516.7638366 , 11136831.64128077, 11624252.15672766,
         14075069.26273247],
        [11780081.29349753, 11966096.78727446, 14232076.05656009,
         10397924.16669749, 11624252.15672766, 12145826.2645139 ,
         14766233.02574041],
        [14281180.86123177, 145310

#### Invert XTX.

In [160]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 6.27784782e+08,  4.52348582e+08, -5.52589667e+08,
        -5.04518657e+08, -1.36497506e+08, -9.70745174e+07,
         2.07769569e+08],
       [ 6.52427761e+08,  1.18496810e+09, -8.15933475e+08,
        -7.54720098e+08, -7.08834488e+08,  2.53306835e+08,
         1.86771033e+08],
       [-4.82034184e+08, -5.85397198e+08,  3.79915957e+08,
         6.66310906e+08,  1.18051009e+08, -1.47095872e+08,
         5.16329750e+07],
       [-4.86725764e+08, -5.86851309e+08,  7.06448581e+08,
         6.82137781e+08,  2.06347119e+08, -3.29606193e+08,
        -1.88697388e+08],
       [-2.37576087e+08, -7.37561522e+08,  2.26902495e+08,
         2.89910408e+08,  1.50145296e+08,  3.48995157e+08,
        -4.08718420e+07],
       [-2.28618838e+08,  1.97697960e+08, -2.05812130e+07,
        -2.25519129e+08,  3.60824331e+08, -2.92220029e+06,
        -8.08263491e+07],
       [ 1.52870693e+08,  7.43387198e+07,  7.67225188e+07,
        -1.51179749e+08,  9.23761238e+06, -2.62872552e+07,
        -1.3533841

#### Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].


In [161]:

Y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
Y


array([1100, 1300,  800,  900, 1000, 1100, 1200])

#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.



In [162]:
X.shape, XTX.shape, inverse_XTX.shape

((7, 2), (7, 7), (7, 7))

In [163]:
X.T.shape

(2, 7)

In [164]:
S= np.dot(X.T, inverse_XTX)
S
S.shape

(2, 7)

In [165]:
S

array([[ 6.10351562e-04,  1.28173828e-03,  1.22070312e-04,
        -1.95312500e-03, -5.34057617e-04, -1.52587891e-05,
         4.88281250e-04],
       [ 1.22070312e-04, -1.86157227e-03,  7.62939453e-04,
         1.70898438e-03,  3.47137451e-04,  2.97546387e-04,
        -6.40869141e-04]])

In [166]:
Y.shape

(7,)

In [167]:
Y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [168]:
S.shape

(2, 7)

In [169]:
W = np.dot(S, Y)

In [170]:
W

array([ 0.71258545, -0.23193359])

#### What's the sum of all the elements of the result?

In [171]:
W.sum()

np.float64(0.48065185546875)