# lesson

https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/03-classification/

and homework is in:

https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2025/03-classification/homework.md




## lesson 3.2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
!wget $data -O data-week-3.csv 
import wget


SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2025-10-13 22:57:43--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com|185.199.111.133|:443... connected.
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Unable to establish SSL connection.


# 0 download the data



In [3]:
!pip install wget

In [4]:
import wget
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv"
wget.download(url)


100% [..............................................................................] 80876 / 80876

'course_lead_scoring (1).csv'

In [5]:
### Load the data
import pandas as pd

data ='course_lead_scoring.csv'

df = pd.read_csv(data)

In [6]:
df.shape

(1462, 9)

# Question 1

What is the most frequent observation (mode) for the column industry?

- NA
- technology
- healthcare
- retail


In [7]:
df.columns


Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [8]:
df['industry'].describe()

count       1328
unique         7
top       retail
freq         203
Name: industry, dtype: object

In [9]:
df['industry'].mode()

0    retail
Name: industry, dtype: object

# Question 2

In [10]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [11]:
features = ['interaction_count', 'number_of_courses_viewed']

In [13]:
df[features].corrwith(df.lead_score)

interaction_count           0.009888
number_of_courses_viewed   -0.004879
dtype: float64

In [14]:
features = ['number_of_courses_viewed' , 'annual_income' ]

In [15]:
df[features].corrwith(df.interaction_count)

number_of_courses_viewed   -0.023565
annual_income               0.048618
dtype: float64

# Question 3. Biggest MI (1 point)



## Split the data

Split the data
Split your data in train/val/test sets with 60%/20%/20% distribution.

Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.

Make sure that the target value y is not in your dataframe.


In [25]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [123]:
df=df.dropna()

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [126]:

len(df_train), len(df_val), len(df_test)


(572, 191, 191)

In [127]:

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

## Q3 
Calculate the mutual information score between y and other categorical variables in the dataset. Use the training set only.

    Round the scores to 2 decimals using round(score, 2).

    Which of these variables has the biggest mutual information score?


In [32]:
from sklearn.metrics import mutual_info_score

In [20]:
df_full_train.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [21]:
categorical = ['industry', 'location', 'lead_score','employment_status' ]

In [42]:
idx = df_full_train.index[df_full_train.isnull().all(1)]
idx

Index([], dtype='int64')

In [45]:
df_full_train.industry.value_counts()

industry
finance          167
retail           166
other            155
healthcare       150
education        143
manufacturing    140
technology       135
Name: count, dtype: int64

In [49]:
df_full_train.isnull().values.any()


np.True_

In [57]:
print(df_full_train[['industry', 'converted']].isnull().sum())
print(df_full_train['converted'].isnull().sum())
df_full_train_cleaned = df_full_train.dropna(subset=['industry', 'converted'])
df_full_train_cleaned.shape

industry     113
converted      0
dtype: int64
0


(1056, 9)

In [46]:
df_full_train.converted.value_counts()

converted
1    710
0    459
Name: count, dtype: int64

In [44]:
df_full_train.converted.describe()

count    1169.000000
mean        0.607357
std         0.488548
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: converted, dtype: float64

In [59]:
mutual_info_score(df_full_train_cleaned.industry, df_full_train_cleaned.converted)

0.012325218199753032

In [60]:
df_full_train_cleaned = df_full_train.dropna(subset=['location', 'converted'])
df_full_train_cleaned.shape
mutual_info_score(df_full_train_cleaned.location, df_full_train_cleaned.converted)

0.001824120225323772

In [61]:
df_full_train_cleaned = df_full_train.dropna(subset=['lead_source', 'converted'])
df_full_train_cleaned.shape
mutual_info_score(df_full_train_cleaned.lead_source, df_full_train_cleaned.converted)

0.027361226871026753

In [62]:
df_full_train_cleaned = df_full_train.dropna(subset=['employment_status', 'converted'])
df_full_train_cleaned.shape
mutual_info_score(df_full_train_cleaned.employment_status, df_full_train_cleaned.converted)

0.014061236226747764

# Question 4

## prepare cat

In [106]:
df_train = df_train.dropna()

In [107]:
df_val = df_val.dropna()

In [128]:
from sklearn.feature_extraction import DictVectorizer

In [129]:
df_train.dtypes, df_train.columns

(lead_source                  object
 industry                     object
 number_of_courses_viewed      int64
 annual_income               float64
 employment_status            object
 location                     object
 interaction_count             int64
 lead_score                  float64
 dtype: object,
 Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
        'employment_status', 'location', 'interaction_count', 'lead_score'],
       dtype='object'))

In [130]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']

In [131]:
dicts = df_train[categorical].to_dict(orient='records')

In [132]:
dicts

[{'lead_source': 'events',
  'industry': 'education',
  'employment_status': 'unemployed',
  'location': 'europe'},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'africa'},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'south_america'},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'africa'},
 {'lead_source': 'paid_ads',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'europe'},
 {'lead_source': 'events',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'south_america'},
 {'lead_source': 'referral',
  'industry': 'manufacturing',
  'employment_status': 'student',
  'location': 'asia'},
 {'lead_source': 'events',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'asia'},
 {'lead_source': 'referral',
  'industry': 'retail',
  

In [133]:
dv = DictVectorizer(sparse=True)


In [134]:
dv.fit(dicts)

DictVectorizer()

In [135]:
df_train.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
dtype: object

In [136]:
numerical = ['number_of_courses_viewed',  'annual_income' , 'interaction_count', 'lead_score' ]

In [137]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [138]:
X_val

array([[4.0344e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [4.7144e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.6615e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       ...,
       [7.7534e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        2.0000e+00],
       [5.4103e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        1.0000e+00],
       [5.6004e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00]], shape=(191, 27))

## train 

In [139]:
from sklearn.linear_model import LogisticRegression

In [140]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [141]:
model.predict(X_train)

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [142]:
y_pred = model.predict_proba(X_val)[:, 1]

In [143]:
y_pred

array([0.83043963, 0.82754566, 0.67087276, 0.87615238, 0.76752153,
       0.30407755, 0.83269022, 0.89097529, 0.74149364, 0.80124866,
       0.91183246, 0.67922912, 0.88061259, 0.44818099, 0.78543618,
       0.55304898, 0.79732749, 0.58189827, 0.62599171, 0.98816389,
       0.82243029, 0.83308781, 0.42673067, 0.28547903, 0.67305651,
       0.58472182, 0.60268792, 0.96896367, 0.3669045 , 0.85478699,
       0.65731666, 0.15741741, 0.94998514, 0.88902611, 0.97989917,
       0.55734287, 0.57573912, 0.6137166 , 0.79611072, 0.78052028,
       0.87830518, 0.78772145, 0.88038626, 0.89655333, 0.22676212,
       0.83485475, 0.50548995, 0.93367146, 0.97723694, 0.51652348,
       0.7856433 , 0.87321411, 0.77999207, 0.28905374, 0.76088002,
       0.80294957, 0.81764589, 0.27004838, 0.5462053 , 0.43848103,
       0.34014125, 0.94491633, 0.95449118, 0.86427214, 0.82956282,
       0.8349915 , 0.6653341 , 0.77099309, 0.63189743, 0.75020151,
       0.77172486, 0.49001057, 0.40421085, 0.25798355, 0.87717

In [145]:
converted_decision = (y_pred >= 0.5) 
converted_decision

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True, False,  True,  True, False, False,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [146]:
(y_val == converted_decision).mean()

np.float64(0.7905759162303665)

In [147]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = converted_decision.astype(int)
df_pred['actual'] = y_val

In [148]:
df_pred['correct'] = df_pred.prediction == df_pred.actual

In [149]:
df_pred

probability  prediction  actual  correct
0       0.830440           1       1     True
1       0.827546           1       0    False
2       0.670873           1       1     True
3       0.876152           1       1     True
4       0.767522           1       1     True
..           ...         ...     ...      ...
186     0.787799           1       1     True
187     0.545530           1       1     True
188     0.380344           0       0     True
189     0.591505           1       0    False
190     0.435369           0       0     True

[191 rows x 4 columns]

In [150]:
df_pred.correct.mean()

np.float64(0.7905759162303665)