# lesson

https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/03-classification/

and homework is in:

https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2025/03-classification/homework.md




## lesson 3.2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
!wget $data -O data-week-3.csv 
import wget


SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2025-10-13 22:57:43--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com|185.199.111.133|:443... connected.
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Unable to establish SSL connection.


# 0 download the data



In [3]:
!pip install wget

In [4]:
import wget
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv"
wget.download(url)


100% [..............................................................................] 80876 / 80876

'course_lead_scoring (1).csv'

In [1]:
### Load the data
import pandas as pd

data ='course_lead_scoring.csv'

df = pd.read_csv(data)

In [2]:
df.shape

(1462, 9)

# Question 1

What is the most frequent observation (mode) for the column industry?

- NA
- technology
- healthcare
- **retail**


In [3]:
df.columns


Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [4]:
df['industry'].describe()

count       1328
unique         7
top       retail
freq         203
Name: industry, dtype: object

In [5]:
df['industry'].mode()

0    retail
Name: industry, dtype: object

# Question 2

Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- interaction_count and lead_score
- number_of_courses_viewed and lead_score
- number_of_courses_viewed and interaction_count
- **annual_income and interaction_count**

Only consider the pairs above when answering this question.

In [6]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [7]:
features = ['interaction_count', 'number_of_courses_viewed']

In [8]:
df[features].corrwith(df.lead_score)

interaction_count           0.009888
number_of_courses_viewed   -0.004879
dtype: float64

In [9]:
features = ['number_of_courses_viewed' , 'annual_income' ]

In [10]:
df[features].corrwith(df.interaction_count)

number_of_courses_viewed   -0.023565
annual_income               0.048618
dtype: float64

# Question 3. Biggest MI (1 point)



## Split the data

Split the data
Split your data in train/val/test sets with 60%/20%/20% distribution.

Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.

Make sure that the target value y is not in your dataframe.


In [12]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [13]:
df=df.dropna()

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [16]:

len(df_train), len(df_val), len(df_test)


(572, 191, 191)

In [17]:

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

## Q3 
Calculate the mutual information score between y and other categorical variables in the dataset. Use the training set only.

    Round the scores to 2 decimals using round(score, 2).

    Which of these variables has the biggest mutual information score?

    Which of these variables has the biggest mutual information score?

- industry
- location
- **lead_source**
- employment_status


In [18]:
from sklearn.metrics import mutual_info_score

In [19]:
df_full_train.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [20]:
categorical = ['industry', 'location', 'lead_score','employment_status' ]

In [21]:
idx = df_full_train.index[df_full_train.isnull().all(1)]
idx

Index([], dtype='int64')

In [22]:
df_full_train.industry.value_counts()

industry
retail           127
finance          116
other            111
education        110
manufacturing    108
healthcare       100
technology        91
Name: count, dtype: int64

In [23]:
df_full_train.isnull().values.any()


np.False_

In [24]:
print(df_full_train[['industry', 'converted']].isnull().sum())
print(df_full_train['converted'].isnull().sum())
df_full_train_cleaned = df_full_train.dropna(subset=['industry', 'converted'])
df_full_train_cleaned.shape

industry     0
converted    0
dtype: int64
0


(763, 9)

In [25]:
df_full_train.converted.value_counts()

converted
1    486
0    277
Name: count, dtype: int64

In [26]:
df_full_train.converted.describe()

count    763.000000
mean       0.636959
std        0.481192
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: converted, dtype: float64

### Industry

In [32]:
round(mutual_info_score(df_full_train_cleaned.industry, df_full_train_cleaned.converted),2)

0.01

### Location 

In [33]:
df_full_train_cleaned = df_full_train.dropna(subset=['location', 'converted'])
df_full_train_cleaned.shape
round(mutual_info_score(df_full_train_cleaned.location, df_full_train_cleaned.converted),2)

0.0

### Lead_source

In [31]:
df_full_train_cleaned = df_full_train.dropna(subset=['lead_source', 'converted'])
df_full_train_cleaned.shape
round(mutual_info_score(df_full_train_cleaned.lead_source, df_full_train_cleaned.converted),2)

0.03

### employment_status

In [30]:
df_full_train_cleaned = df_full_train.dropna(subset=['employment_status', 'converted'])
df_full_train_cleaned.shape
round(mutual_info_score(df_full_train_cleaned.employment_status, df_full_train_cleaned.converted), 2)

0.01

# Question 4

## prepare cat

In [34]:
df_train = df_train.dropna()

In [35]:
df_val = df_val.dropna()

In [36]:
from sklearn.feature_extraction import DictVectorizer

In [37]:
df_train.dtypes, df_train.columns

(lead_source                  object
 industry                     object
 number_of_courses_viewed      int64
 annual_income               float64
 employment_status            object
 location                     object
 interaction_count             int64
 lead_score                  float64
 dtype: object,
 Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
        'employment_status', 'location', 'interaction_count', 'lead_score'],
       dtype='object'))

In [38]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']

In [39]:
dicts = df_train[categorical].to_dict(orient='records')

In [58]:
#dicts

In [41]:
dv = DictVectorizer(sparse=True)


In [42]:
dv.fit(dicts)

DictVectorizer()

In [43]:
df_train.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
dtype: object

In [44]:
numerical = ['number_of_courses_viewed',  'annual_income' , 'interaction_count', 'lead_score' ]

In [45]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [46]:
X_val

array([[4.0344e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [4.7144e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.6615e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       ...,
       [7.7534e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        2.0000e+00],
       [5.4103e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        1.0000e+00],
       [5.6004e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00]], shape=(191, 27))

## train 

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [49]:
model.predict(X_train)

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [50]:
y_pred = model.predict_proba(X_val)[:, 1]

In [52]:
converted_decision = (y_pred >= 0.5) 
converted_decision

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True, False,  True,  True, False, False,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [53]:
(y_val == converted_decision).mean()

np.float64(0.7905759162303665)

In [54]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = converted_decision.astype(int)
df_pred['actual'] = y_val

In [55]:
df_pred['correct'] = df_pred.prediction == df_pred.actual

In [56]:
df_pred

probability  prediction  actual  correct
0       0.830440           1       1     True
1       0.827546           1       0    False
2       0.670873           1       1     True
3       0.876152           1       1     True
4       0.767522           1       1     True
..           ...         ...     ...      ...
186     0.787799           1       1     True
187     0.545530           1       1     True
188     0.380344           0       0     True
189     0.591505           1       0    False
190     0.435369           0       0     True

[191 rows x 4 columns]

In [57]:
df_pred.correct.mean()

np.float64(0.7905759162303665)

# Question 5


Let's find the least useful feature using the feature elimination technique.

Train a model using the same features and parameters as in Q4 (without rounding).

Now exclude each feature from this set and train a model without it. 

Record the accuracy for each model.

For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

Which of following feature has the smallest difference?

- 'industry'
- 'employment_status'
- 'lead_score'

Note: The difference doesn't have to be positive.

In [66]:
from sklearn.feature_extraction import DictVectorizer
df_train.dtypes, df_train.columns



(lead_source                  object
 industry                     object
 number_of_courses_viewed      int64
 annual_income               float64
 employment_status            object
 location                     object
 interaction_count             int64
 lead_score                  float64
 dtype: object,
 Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
        'employment_status', 'location', 'interaction_count', 'lead_score'],
       dtype='object'))

In [98]:

categorical = [ 'industry', 'employment_status', 'location'] #['lead_source', 'industry', 'employment_status', 'location']
dicts = df_train[categorical].to_dict(orient='records')
dv = DictVectorizer(sparse=True)




In [99]:
numerical = ['number_of_courses_viewed',  'annual_income' , 'interaction_count', 'lead_score' ]
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)


In [100]:

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [101]:

model.predict(X_train)
y_pred = model.predict_proba(X_val)[:, 1]
converted_decision = (y_pred >= 0.5) 
converted_decision


array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False, False, False,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [102]:

(y_val == converted_decision).mean()


np.float64(0.7853403141361257)

In [103]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = converted_decision.astype(int)
df_pred['actual'] = y_val
df_pred['correct'] = df_pred.prediction == df_pred.actual

In [104]:
df_pred.correct.mean()

np.float64(0.7853403141361257)

In [110]:
diff_industry =  abs(0.7958115183246073 - 0.7905759162303665 )
diff_industry

0.005235602094240788

In [83]:
diff_employment = abs(0.8010471204188482 - 0.7905759162303665)
diff_employment

0.010471204188481686

In [105]:
diff_lead_score = abs(0.7853403141361257 - 0.7905759162303665)

In [106]:
diff_lead_score

0.005235602094240788

In [109]:
#diff_industry LT diff_lead_score
print(diff_industry == diff_lead_score)

True


# Question 6

Now let's train a regularized logistic regression.

Let's try the following values of the parameter C: [0.01, 0.1, 1, 10, 100].

Train models using all the features as in Q4.

Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these C leads to the best accuracy on the validation set?

In [111]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']
dicts = df_train[categorical].to_dict(orient='records')
dv = DictVectorizer(sparse=True)
df_train.dtypes

numerical = ['number_of_courses_viewed',  'annual_income' , 'interaction_count', 'lead_score' ]
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)


In [113]:
C = [0.01, 0.1, 1, 10, 100]

In [116]:
accuracy_list = []
for c in C:
    print(c)
    model = LogisticRegression(solver='liblinear', C=c, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    model.predict(X_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    converted_decision = (y_pred >= 0.5) 
    #converted_decision

    (y_val == converted_decision).mean()
    df_pred = pd.DataFrame()
    df_pred['probability'] = y_pred
    df_pred['prediction'] = converted_decision.astype(int)
    df_pred['actual'] = y_val
    df_pred['correct'] = df_pred.prediction == df_pred.actual
    print(df_pred.correct.mean())
    accuracy_list.append([c,df_pred.correct.mean() ])

print(accuracy_list)

0.01
0.6596858638743456
0.1
0.7905759162303665
1
0.7905759162303665
10
0.7905759162303665
100
0.7958115183246073
[[0.01, np.float64(0.6596858638743456)], [0.1, np.float64(0.7905759162303665)], [1, np.float64(0.7905759162303665)], [10, np.float64(0.7905759162303665)], [100, np.float64(0.7958115183246073)]]


In [117]:
sorted_matrix = sorted(accuracy_list, key=lambda row: row[1])

In [118]:
sorted_matrix

[[0.01, np.float64(0.6596858638743456)],
 [0.1, np.float64(0.7905759162303665)],
 [1, np.float64(0.7905759162303665)],
 [10, np.float64(0.7905759162303665)],
 [100, np.float64(0.7958115183246073)]]